name: New Code Freeze
on:
    release:
        types: [released]

permissions: {}

env:
    GIT_COMMITTER_NAME: 'WooCommerce Bot'
    GIT_COMMITTER_EMAIL: 'no-reply@woocommerce.com'
    GIT_AUTHOR_NAME: 'WooCommerce Bot'
    GIT_AUTHOR_EMAIL: 'no-reply@woocommerce.com'

jobs:
    verify-release:
        name: 'Verify if the release is a major version release, that ends with .0'
        runs-on: ubuntu-20.04
        outputs:
            run: ${{ steps.verify.outputs.run }}
        steps:
            - name: Verify release
              id: verify
              uses: actions/github-script@v6
              with:
                  script: |
                      const event = context.payload;
                      const release = event.release;

                      if (release.tag_name.endsWith('.0')) {
                          core.setOutput('run', 'true');
                      } else {
                          core.setOutput('run', 'false');
                      }

            - name: Verify if any PR is left open by author:app/github-actions
              id: verify-prs
              uses: actions/github-script@v6
              with:
                  script: |
                      const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
                      const prs = await github.rest.pulls.list({ owner, repo, state: 'open', author: 'app/github-actions' });
                      if (prs.data.length > 0) {
                          core.setOutput('prs-left-open-count', prs.data.length);
                          core.setFailed(`Found ${prs.data.length} open PRs from github-actions bot. Please close them before proceeding.`);
                      }

            - name: Notify Slack on failure
              if: ${{ failure() }}
              uses: archive/github-actions-slack@v2.0.0
              with:
                  slack-bot-user-oauth-access-token: ${{ secrets.CODE_FREEZE_BOT_TOKEN }}
                  slack-channel: ${{ secrets.WOO_RELEASE_SLACK_CHANNEL }}
                  slack-text: |
                      :ice_cube: Code Freeze workflow failed.
                      :warning-8c: There are `${{ steps.verify-prs.outputs.prs-left-open-count }}` PRs left open by `app/github-actions` bot. Please merge them and re-run the workflow. Merging them is essential to maintain the integrity of code across all branches. Workflow run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
    
    prep-for-code-freeze:
        name: 'Prepare for code freeze - generate next release branch and milestone'
        if: needs.verify-release.outputs.run == 'true'
        needs: verify-release
        runs-on: ubuntu-20.04
        outputs:
            nextReleaseBranch: ${{ steps.extract-version.outputs.nextReleaseBranch }}
            nextReleaseVersion: ${{ steps.extract-version.outputs.nextReleaseVersion }}
            milestoneForTrunk: ${{ steps.extract-version.outputs.milestoneForTrunk }}
        steps:
            - name: Extract version from release tag
              id: extract-version
              uses: actions/github-script@v6
              with:
                  script: |
                      const event = context.payload;

                      function bumpMinorVersion(currentVersion) {
                          const [major, minor, patch] = currentVersion.split('.').map(Number);

                          let nextMajor = major;
                          let nextMinor = minor + 1;
                          if (nextMinor > 9) {
                              nextMajor += 1;
                              nextMinor = 0;
                          }

                          return {
                              nextMajor,
                              nextMinor
                          };
                      }

                      const currentReleaseTag = event.release.tag_name;
                      let { nextMajor, nextMinor } = bumpMinorVersion( currentReleaseTag );
                      const nextReleaseVersion = `${nextMajor}.${nextMinor}.0`;
                      const nextReleaseBranch = `release/${nextMajor}.${nextMinor}`;


                      let { nextMajor, nextMinor } = bumpMinorVersion( nextReleaseVersion );
                      const milestoneForTrunk = `${nextMajor}.${nextMinor}.0`;

                      core.setOutput('nextReleaseBranch', nextReleaseBranch);
                      core.setOutput('nextReleaseVersion', nextReleaseVersion);
                      core.setOutput('milestoneForTrunk', milestoneForTrunk);

                      console.log(`Next release branch: ${nextReleaseBranch}`);
                      console.log(`Next release version: ${nextReleaseVersion}`);
                      console.log(`Milestone for trunk: ${milestoneForTrunk}`);
    
    create-code-freeze-branch-and-milestone:
        name: 'Create the code freeze branch and milestone for next release'
        needs: prep-for-code-freeze
        runs-on: ubuntu-20.04
        permissions:
          issues: write
          contents: write
        steps:
            - name: Fetch trunk branch
              uses: actions/checkout@v3
              with:
                ref: trunk

            - name: Setup PNPM
              uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d

            - name: Setup Node
              uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
              with:
                  node-version-file: .nvmrc
                  cache: pnpm
                  registry-url: 'https://registry.npmjs.org'

            - name: Install prerequisites
              run: |
                  pnpm install --filter monorepo-utils --ignore-scripts
                  # ignore scripts speeds up setup signficantly, but we still need to build monorepo utils
                  pnpm build
              working-directory: tools/monorepo-utils

            - name: Create code freeze branch out of trunk
              env:
                RELEASE_BRANCH: ${{ needs.prep-for-code-freeze.outputs.nextReleaseBranch }}
              run: |
                  git checkout trunk
                  git checkout -b $RELEASE_BRANCH

            - name: Push the new branch to the remote repository
              env:
                RELEASE_BRANCH: ${{ needs.prep-for-code-freeze.outputs.nextReleaseBranch }}
              run: git push origin $RELEASE_BRANCH

            - name: Create next monthly milestone
              id: milestone
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: pnpm utils code-freeze milestone -o ${{ github.repository_owner }} -m ${{ needs.prep-for-code-freeze.outputs.milestoneForTrunk }}

            - name: Bump versions for Beta.1 monthly release
              id: version-bump
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: pnpm utils code-freeze version-bump -o ${{ github.repository_owner }} -b ${{ needs.prep-for-code-freeze.outputs.nextReleaseBranch }} -c ${{ needs.prep-for-code-freeze.outputs.nextReleaseVersion }}-beta.1

            - name: Prepare trunk for next development cycle
              id: prep-trunk
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: pnpm utils code-freeze version-bump ${{ needs.prep-for-code-freeze.outputs.milestoneForTrunk }}-dev -o ${{ github.repository_owner }}

            - name: Notify Slack on success
              if: ${{ success() }}
              uses: archive/github-actions-slack@v2.0.0
              with:
                  slack-bot-user-oauth-access-token: ${{ secrets.CODE_FREEZE_BOT_TOKEN }}
                  slack-channel: ${{ secrets.WOO_RELEASE_SLACK_CHANNEL }}
                  slack-text: |
                      :ice_cube: Code Freeze completed for `${{ needs.prep-for-code-freeze.outputs.nextReleaseBranch }}` :checking:
                      You can raise a code freeze exception if you need something to be included in this release.
                  slack-optional-unfurl_links: false
                  slack-optional-unfurl_media: false

            - name: Notify Slack on failure
              if: ${{ failure() }}
              uses: archive/github-actions-slack@v2.0.0
              with:
                  slack-bot-user-oauth-access-token: ${{ secrets.CODE_FREEZE_BOT_TOKEN }}
                  slack-channel: ${{ secrets.WOO_RELEASE_SLACK_CHANNEL }}
                  slack-text: |
                      :warning-8c: Code freeze failed for `${{ needs.prep-for-code-freeze.outputs.nextReleaseBranch }}`. Please check the logs for more details. Workflow run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

    changelog-version-update-for-trunk:
        name: Update changelog and version for trunk
        runs-on: ubuntu-20.04
        needs: [create-code-freeze-branch-and-milestone]
        permissions:
          contents: write
          pull-requests: write
        steps:
            - uses: actions/checkout@v3
              with:
                ref: trunk

            - name: Copy readme.txt to vm root
              run: cp ./plugins/woocommerce/readme.txt ../../readme.txt

            - name: Switch to trunk branch
              run: git checkout trunk

            - name: Create a new branch based on trunk
              run: git checkout -b prep/post-release-tasks-${{ github.event.release.tag_name }}

            - name: Check if we need to continue processing
              uses: actions/github-script@v6
              id: check
              with:
                  script: |
                      const fs = require( 'node:fs' );
                      const version = context.payload.release.tag_name;

                      fs.readFile( './plugins/woocommerce/readme.txt', 'utf-8', function( err, data ) {
                        if ( err ) {
                          console.error( err );
                        }

                        const regex = /Stable\stag:\s(\d+\.\d+\.\d+)/;

                        const stableVersion = data.match( regex )[1];

                        // If the release version is less than stable version we can bail.
                        if ( version.localeCompare( stableVersion, undefined, { numeric: true, sensitivity: 'base' } ) == -1 ) {
                          console.log( 'Release version is less than stable version. No automated action taken. A manual process is required.' );
                          core.setOutput( 'continue', 'false' )
                          return;
                        } else {
                          core.setOutput( 'continue', 'true' )
                        }
                      } )

            - name: Update changelog.txt entries
              uses: actions/github-script@v6
              id: update-entries
              if: steps.check.outputs.continue == 'true'
              with:
                  script: |
                      const fs = require( 'node:fs' );
                      const version = context.payload.release.tag_name;

                      // Read the saved readme.txt file from earlier.
                      fs.readFile( '../../readme.txt', 'utf-8', function( err, readme ) {
                        if ( err ) {
                          core.setFailed( err );
                        }

                        const regex = /(== Changelog ==[\s\S]+)\s{2}\[See changelog for all versions\]\(https:\/\/raw\.githubusercontent\.com\/woocommerce\/woocommerce\/trunk\/changelog\.txt\)\./;

                        const entries = readme.match( regex )[1];

                        fs.readFile( './changelog.txt', 'utf-8', function( err, changelog ) {
                          if ( err ) {
                            core.setFailed( err );
                          }

                          const regex = /== Changelog ==/;

                          const updatedChangelog = changelog.replace( regex, entries );

                          fs.writeFile( './changelog.txt', updatedChangelog, err => {
                            if ( err ) {
                              core.setFailed( err );
                            }
                          } )
                        } )
                      } )

            - name: Commit changes
              id: commit-changes
              run: |
                git commit -am "Prep post release ${{ github.event.release.tag_name }}"
                commit_sha=$(git rev-parse HEAD)
                echo "::set-output name=commit_hash::${commit_sha}"

            - name: Push branch up
              run: git push origin prep/post-release-tasks-${{ github.event.release.tag_name }}

            - name: Create the PR
              uses: actions/github-script@v6
              with:
                  script: |
                      const body = "This PR updates the changelog.txt entries for trunk based on the latest release: ${{ github.event.release.tag_name }}"

                      const pr = await github.rest.pulls.create({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        title: "Update changelog.txt from release ${{ github.event.release.tag_name }}",
                        head: "prep/post-release-tasks-${{ github.event.release.tag_name }}",
                        base: "trunk",
                        body: body
                      })

                      const prCreated = await github.rest.pulls.requestReviewers({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        pull_number: pr.data.number,
                        reviewers: ["${{ github.event.release.author.login }}"]
                      })
